"""GitHub API integration for posting inline PR review comments.

Uses `gh api` to post PR reviews with inline comments via the
GitHub REST API: POST /repos/{owner}/{repo}/pulls/{pr}/reviews
"""

import json
import subprocess
from dataclasses import dataclass

from agent import InlineComment


@dataclass
class ReviewResult:
    """Result of posting a review to GitHub."""
    success: bool
    review_url: str = ""
    error: str = ""


def get_repo_owner_name(repo_path: str = ".") -> tuple[str, str]:
    """Get the owner and repo name from the local git remote.

    Returns (owner, repo_name).
    """
    result = subprocess.run(
        ["gh", "repo", "view", "--json", "owner,name"],
        capture_output=True,
        text=True,
        cwd=repo_path,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to get repo info: {result.stderr}")

    data = json.loads(result.stdout)
    return data["owner"]["login"], data["name"]


def post_inline_review(
    pr_number: int,
    comments: list[InlineComment],
    body: str = "",
    event: str = "COMMENT",
    repo_path: str = ".",
) -> ReviewResult:
    """Post a PR review with inline comments.

    Args:
        pr_number: The PR number.
        comments: List of InlineComment objects to post.
        body: Top-level review body text.
        event: Review event type: COMMENT, APPROVE, or REQUEST_CHANGES.
        repo_path: Path to the git repository.

    Returns:
        ReviewResult with success status and URL or error.
    """
    owner, repo = get_repo_owner_name(repo_path)

    # Build the comments payload
    comments_payload = []
    for c in comments:
        entry = {
            "path": c.path,
            "position": c.position,
            "body": _format_comment_body(c),
        }
        comments_payload.append(entry)

    payload = {
        "body": body or _generate_review_body(comments),
        "event": event,
        "comments": comments_payload,
    }

    # Use gh api to post the review
    api_path = f"repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    result = subprocess.run(
        [
            "gh", "api",
            "--method", "POST",
            api_path,
            "--input", "-",
        ],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        cwd=repo_path,
    )

    if result.returncode != 0:
        return ReviewResult(
            success=False,
            error=f"gh api failed: {result.stderr}",
        )

    try:
        data = json.loads(result.stdout)
        review_url = data.get("html_url", "")
        return ReviewResult(success=True, review_url=review_url)
    except json.JSONDecodeError:
        return ReviewResult(success=True)


def _format_comment_body(comment: InlineComment) -> str:
    """Format a single inline comment with severity indicator."""
    severity_icons = {
        "critical": "CRITICAL",
        "important": "IMPORTANT",
        "suggestion": "SUGGESTION",
    }
    icon = severity_icons.get(comment.severity, "NOTE")
    return f"[{icon}] {comment.body}"


def _generate_review_body(comments: list[InlineComment]) -> str:
    """Generate a summary review body from the list of comments."""
    total = len(comments)
    critical = sum(1 for c in comments if c.severity == "critical")
    important = sum(1 for c in comments if c.severity == "important")
    suggestion = sum(1 for c in comments if c.severity == "suggestion")

    parts = ["## AI Code Review Summary", ""]

    if critical:
        parts.append(f"- **Critical:** {critical} issue(s) that must be addressed")
    if important:
        parts.append(f"- **Important:** {important} issue(s) that should be addressed")
    if suggestion:
        parts.append(f"- **Suggestion:** {suggestion} improvement(s)")

    parts.append("")
    parts.append(f"Total: {total} comment(s) across the PR.")
    parts.append("")
    parts.append("---")
    parts.append("*Generated by [AI PR Reviewer](https://github.com/AkiraKane/ai-pr-reviewer)*")

    return "\n".join(parts)
